### PR TITLE
Pulled main BossView functionality into a mixin.  This was inspired by c...

### PR DESCRIPTION
**Pull request by erikahlswede**
Added Marionette.CompositeView BossView.  Pulled out main BossView functionality into a mixin and use it in both the ItemView and CompositeView BossView definition. 

If this is something you are interested in, I can clean up test cases and right new ones for the Mixin/CompositeView

The mixins can be made very simple if a mixin library such as CocktailJS is introduced:
https://github.com/onsi/cocktail

### CODE REVIEW

**Comment by tinymammothdesign** [comment]
Bump! ;)

**Comment by justspamjustin** [comment]
@erikahlswede I added you as a contributor to the repo. I apologize it took me so long to get on this. We are no longer using BossView at my work. But if you are still using it, please help keep it moving forward. Thanks.

**Comment by agwidarsito** [comment]
We have a commit here, can we merge it in? ^^

**Comment by erikahlswede** [comment]
Many months later, going to close this and re-roll a clean pull request

**Pull request closed without merging**
